USE [bdpetsystem]
GO

/****** Object:  Table [dbo].[TB_PET]    Script Date: 27/03/2015 17:59:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_PET](
	[codigo] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](50) NULL,
	[raca] [nvarchar](50) NULL,
 CONSTRAINT [PK_TB_PET] PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


